version: '3'

services:

  app:
    build: 
      context: ./nodejs
      dockerfile: Dockerfile
    image: 'douglasmarinhosilva/nodejsdesafio'
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh 
    command: [ "node","index.js" ]
    container_name: app
    networks:
      - desafio-fullcycle
    tty: true
    
    depends_on:
      - db
      
     
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: 'douglasmarinhosilva/nginxdesafio'
    container_name: nginx
    networks:
      - desafio-fullcycle
    tty: true
    ports:
      - 8080:80
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/:/var/lib/mysql
    ports:
      - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycledb
    networks:
      - desafio-fullcycle


networks:
  desafio-fullcycle:
    driver: bridge